[package]
name = "read_files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.6.0"
csv = "1.2.0"
serde = { version = "1.0.152", features = ["serde_derive"] }
